package vn.io.huangnosimp.constants

const val MC_VERSION_MANIFEST_V2_URL = "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json"
const val PAPERMC_REPOSITORY_URL = "https://repo.papermc.io/repository/maven-public/"
const val MACHE_METADATA_URL = PAPERMC_REPOSITORY_URL + "io/papermc/mache/maven-metadata.xml"

const val CONDUIT_CACHE_DIR = ".gradle/conduit/"
const val BASE_DIR = "base/"
const val MACHE_DIR = "mache/"
const val MC_MANIFEST = CONDUIT_CACHE_DIR + "mcManifest.json"
const val VERSION_MANIFEST = "versionManifest.json"
const val BUNDLER_JAR = "jars/bundler.jar"
const val DECOMPILED_JAR = "jars/decompiled_server.jar"
const val SERVER_JAR = "jars/server.jar"
const val LIBS_DIR = "libs"
const val SOURCES_DIR = "minecraft/java"
const val RESOURCES_DIR = "minecraft/resources"
const val WORKSPACE_SOURCES_DIR = "src/minecraft/java"
const val WORKSPACE_RESOURCES_DIR = "src/minecraft/resources"
const val MACHE_PATCHES_DIR = "patches"
const val MACHE_JSON = "mache.json"

const val CONDUIT = "conduit"

const val MACHE_CODEBOOK_CONFIG = "macheCodebook"
const val MACHE_PARAM_MAPPINGS_CONFIG = "macheParamMappings"
const val MACHE_CONSTANTS_CONFIG = "macheConstants"
const val MACHE_REMAPPER_CONFIG = "macheRemapper"
const val MACHE_DECOMPILER_CONFIG = "macheDecompiler"

const val DOWNLOAD_MC_MANIFEST = "downloadMcManifest"
const val DOWNLOAD_VERSION_MANIFEST = "downloadVersionManifest"
const val DOWNLOAD_BUNDLE_JAR = "downloadBundleJar"
const val EXTRACT_BUNDLE_JAR = "extractBundleJar"
const val EXTRACT_MACHE = "extractMache"
