package vn.io.huangnosimp.constants

const val MC_VERSION_MANIFEST_V2_URL = "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json"
const val PAPERMC_REPOSITORY_URL = "https://repo.papermc.io/repository/maven-public/"
const val MACHE_METADATA_URL = PAPERMC_REPOSITORY_URL + "io/papermc/mache/maven-metadata.xml"

// Base Directory
const val CONDUIT_CACHE_DIR = ".gradle/conduit/"
const val BASE_DIR = CONDUIT_CACHE_DIR + "base/"
const val JAR_DIR = BASE_DIR + "jars/"
const val MACHE_DIR = BASE_DIR + "mache/"
const val MC_MANIFEST = CONDUIT_CACHE_DIR + "mcManifest.json"
const val VERSION_MANIFEST = BASE_DIR + "versionManifest.json"
const val BUNDLER_JAR = JAR_DIR + "bundler.jar"
const val REMAPPED_JAR = JAR_DIR + "remapped_server.jar"
const val SERVER_MAPPING = BASE_DIR + "mojmap.txt"
const val DECOMPILED_JAR = JAR_DIR + "decompiled_server.jar"
const val SERVER_JAR = JAR_DIR + "server.jar"
const val PATCHED_JAR = JAR_DIR + "patched_server.jar"
const val LIBS_DIR = BASE_DIR + "libs"
const val MACHE_PATCHES_DIR = MACHE_DIR + "patches"
const val MACHE_JSON = MACHE_DIR + "mache.json"
const val SOURCES_DIR = "minecraft/java"
const val RESOURCES_DIR = "minecraft/resources"
const val WORKSPACE_SOURCES_DIR = "src/minecraft/java"
const val WORKSPACE_RESOURCES_DIR = "src/minecraft/resources"

const val CONDUIT = "conduit"

const val MACHE_CODEBOOK_CONFIG = "macheCodebook"
const val MACHE_PARAM_MAPPINGS_CONFIG = "macheParamMappings"
const val MACHE_CONSTANTS_CONFIG = "macheConstants"
const val MACHE_REMAPPER_CONFIG = "macheRemapper"
const val MACHE_DECOMPILER_CONFIG = "macheDecompiler"

const val DOWNLOAD_MC_MANIFEST = "downloadMcManifest"
const val DOWNLOAD_VERSION_MANIFEST = "downloadVersionManifest"
const val DOWNLOAD_BUNDLE_JAR = "downloadBundleJar"
const val EXTRACT_BUNDLE_JAR = "extractBundleJar"
const val EXTRACT_MACHE = "extractMache"
const val REMAP_SERVER_JAR = "remapServerJar"
const val DECOMPILE_SERVER_JAR = "decompileServerJar"
const val APPLY_MACHE_PATCHES = "applyMachePatches"
