[versions]
kotlin = "2.4.10"
ktlint = "14.2.0"
gson = "2.14.0"
plugin-publish = "2.2.1"
jgit = "7.7.1.202607240634-r"
diffpatch = "2.1.0.43"
[libraries]
gson = {module = "com.google.code.gson:gson", version.ref = "gson"}
jgit = {module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit"}
diffpatch = {module = "io.codechicken:DiffPatch", version.ref = "diffpatch"}
[plugins]
kotlin-jvm = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ktlint = {id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint"}
plugin-publish = {id = "com.gradle.plugin-publish", version.ref = "plugin-publish"}